export const BuildingData = [
  {
    name: "Cursor",
    description: "Autoclicks once every 10 seconds.",
    price: 15,
    image: "cursor.webp",
    owned: 0,
    cps: 0.1,
    modifier: 1,
  },
  {
    name: "Grandma",
    description: "A nice grandma to bake more cookies.",
    price: 100,
    image: "grandma.webp",
    owned: 0,
    cps: 1,
    modifier: 1,
  },
  {
    name: "Farm",
    description: "Grows cookie plants from cookie seeds.",
    price: 1100,
    image: "farm.webp",
    owned: 0,
    cps: 8,
    modifier: 1,
  },
  {
    name: "Mine",
    description: "Mines out cookie dough and chocolate chips.",
    price: 12e3,
    image: "mine.webp",
    owned: 0,
    cps: 47,
    modifier: 1,
  },
  {
    name: "Factory",
    description: "Produces large quantities of cookies.",
    price: 130e3,
    image: "factory.webp",
    owned: 0,
    cps: 260,
    modifier: 1,
  },
  {
    name: "Bank",
    description: "Generates cookies from interest.",
    price: 1.4e6,
    image: "bank.webp",
    owned: 0,
    cps: 1400,
    modifier: 1,
  },
  {
    name: "Temple",
    description: "Full of precious, ancient chocolate.",
    price: 20e6,
    image: "temple.webp",
    owned: 0,
    cps: 7800,
    modifier: 1,
  },
  {
    name: "Wizard Tower",
    description: "Summons cookies with magic spells.",
    price: 330e6,
    image: "wizard_tower.webp",
    owned: 0,
    cps: 44e3,
    modifier: 1,
  },
  {
    name: "Shipment",
    description: "Brings in fresh cookies from the cookie planet.",
    price: 5.1e9,
    image: "shipment.webp",
    owned: 0,
    cps: 260e3,
    modifier: 1,
  },
  {
    name: "Alchemy Lab",
    description: "Turns gold into cookies!",
    price: 75e9,
    image: "alchemy_lab.webp",
    owned: 0,
    cps: 1.6e6,
    modifier: 1,
  },
  {
    name: "Portal",
    description: "Opens a door to the Cookieverse.",
    price: 1e12,
    image: "portal.webp",
    owned: 0,
    cps: 10e6,
    modifier: 1,
  },
  {
    name: "Time Machine",
    description: "Brings cookies from the past, before they were even eaten.",
    price: 14e12,
    image: "time_machine.webp",
    owned: 0,
    cps: 65e6,
    modifier: 1,
  },
  {
    name: "Antimatter Condenser",
    description: "Condenses the antimatter in the universe into cookies.",
    price: 170e12,
    image: "antimatter_condenser.webp",
    owned: 0,
    cps: 430e6,
    modifier: 1,
  },
  {
    name: "Prism",
    description: "Converts light itself into cookies.",
    price: 2.1e15,
    image: "prism.webp",
    owned: 0,
    cps: 2.9e9,
    modifier: 1,
  },
  {
    name: "Chancemaker",
    description: "Generates cookies out of thin air through sheer luck.",
    price: 26e15,
    image: "chancemaker.webp",
    owned: 0,
    cps: 21e6,
    modifier: 1,
  },
  {
    name: "Fractal Engine",
    description: "Turns cookies into even more cookies.",
    price: 310e15,
    image: "fractal_engine.webp",
    owned: 0,
    cps: 150e9,
    modifier: 1,
  },
  {
    name: "Javascript Console",
    description: "Creates cookies from the very code this game was written in.",
    price: 71e18,
    image: "javascript_console.webp",
    owned: 0,
    cps: 1.1e12,
    modifier: 1,
  },
  {
    name: "Idleverse",
    description: "There's been countless other idle universes running alongside your own. You've finally found a way to hijack their production and convert whatever they've been making into cookies!",
    price: 12e21,
    image: "idleverse.webp",
    owned: 0,
    cps: 8.3e12,
    modifier: 1,
  },
  {
    name: "Cortex Baker",
    description: "These artificial brains the size of planets are capable of simply dreaming up cookies into existence. Time and space are inconsequential. Reality is arbitraray.",
    price: 1.9e24,
    image: "cortex_baker.webp",
    owned: 0,
    cps: 64e12,
    modifier: 1,
  },
  {
    name: "You",
    description: "You, alone, are the reason behind all these cookies. You figure if there were more of you... maybe you could make even more.",
    price: 540e24,
    image: "you.webp",
    owned: 0,
    cps: 510e12,
    modifier: 1,
  }
]