export const BuildingData = [
  {
    name: "Cursor",
    description: "Autoclicks once every 10 seconds.",
    price: 15,
    image: "cursor.webp",
    owned: 0,
    cps: 0.1,
    modifier: 1,
  },
  {
    name: "Grandma",
    description: "A nice grandma to bake more cookies.",
    price: 100,
    image: "grandma.webp",
    owned: 0,
    cps: 1,
    modifier: 1,
  },
  {
    name: "Farm",
    description: "Grows cookie plants from cookie seeds.",
    price: 1100,
    image: "farm.webp",
    owned: 0,
    cps: 8,
    modifier: 1,
  },
  {
    name: "Mine",
    description: "Mines out cookie dough and chocolate chips.",
    price: 12000,
    image: "mine.webp",
    owned: 0,
    cps: 47,
    modifier: 1,
  },
  {
    name: "Factory",
    description: "Produces large quantities of cookies.",
    price: 130000,
    image: "factory.webp",
    owned: 0,
    cps: 260,
    modifier: 1,
  },
  {
    name: "Bank",
    description: "Generates cookies from interest.",
    price: 1400000,
    image: "bank.webp",
    owned: 0,
    cps: 1400,
    modifier: 1,
  },
  {
    name: "Temple",
    description: "Full of precious, ancient chocolate.",
    price: 20000000,
    image: "temple.webp",
    owned: 0,
    cps: 7800,
    modifier: 1,
  },
  {
    name: "Wizard Tower",
    description: "Summons cookies with magic spells.",
    price: 330000000,
    image: "wizard_tower.webp",
    owned: 0,
    cps: 44000,
    modifier: 1,
  },
  {
    name: "Shipment",
    description: "Brings in fresh cookies from the cookie planet.",
    price: 5100000000,
    image: "shipment.webp",
    owned: 0,
    cps: 260000,
    modifier: 1,
  },
  {
    name: "Alchemy Lab",
    description: "Turns gold into cookies!",
    price: 75000000000,
    image: "alchemy_lab.webp",
    owned: 0,
    cps: 1600000,
    modifier: 1,
  },
  {
    name: "Portal",
    description: "Opens a door to the Cookieverse.",
    price: 1000000000000,
    image: "portal.webp",
    owned: 0,
    cps: 10000000,
    modifier: 1,
  },
  {
    name: "Time machine",
    description: "Brings cookies from the past, before they were even eaten.",
    price: 14000000000000,
    image: "time_machine.webp",
    owned: 0,
    cps: 65000000,
    modifier: 1,
  },
  {
    name: "Antimatter Condenser",
    description: "Condenses the antimatter in the universe into cookies.",
    price: 170000000000000,
    image: "antimatter_condenser.webp",
    owned: 0,
    cps: 430000000,
    modifier: 1,
  },
  // {
  //   name: "Prism",
  //   description: "Converts light itself into cookies.",
  //   image: "prism.webp",
  //   owned: 0,
  //   cps: 1,
  //   modifier: 1,
  // },
  // {
  //   name: "Chancemaker",
  //   description: "Generates cookies out of thin air through sheer luck.",
  //   image: "chancemaker.webp",
  //   owned: 0,
  //   cps: 0,
  //   modifier: 1,
  // },
  // {
  //   name: "Fractal engine",
  //   description: "Turns cookies into even more cookies.",
  //   image: "fractal_engine.webp",
  //   owned: 0,
  //   cps: 0,
  //   modifier: 1,
  // },
  // {
  //   name: "Javascript console",
  //   description: "Creates cookies from the very code this game was written in.",
  //   image: "javascript_console.webp",
  //   owned: 0,
  //   cps: 0,
  //   modifier: 1,
  // },
  // {
  //   name: "Idleverse",
  //   description: "There's been countless other idle universes running alongside your own. You've finally found a way to hijack their production and convert whatever they've been making into cookies!",
  //   image: "idleverse.webp",
  //   owned: 0,
  //   cps: 0,
  //   modifier: 1,
  // },
  // {
  //   name: "Cortex baker",
  //   description: "These artificial brains the size of planets are capable of simply dreaming up cookies into existence. Time and space are inconsequential. Reality is arbitraray.",
  //   image: "cortex_baker.webp",
  //   owned: 0,
  //   cps: 0,
  //   modifier: 1,
  // },
  // {
  //   name: "You",
  //   description: "You, alone, are the reason behind all these cookies. You figure if there were more of you... maybe you could make even more.",
  //   image: "you.webp",
  //   owned: 0,
  //   cps: 0,
  //   modifier: 1,
  // }
]