export const AlchemyLabUpgrades = [
  {
    name: "Antimony",
    description: "Alchemy labs are twice as efficient.",
    price: 750e9,
    image: "alchemy_lab/plain_alchemy_lab.webp",
    modifying: {
      building: "Alchemy Lab",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Alchemy Lab",
      amount: 1,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "Essence of dough",
    description: "Alchemy labs are twice as efficient.",
    price: 3.75e12,
    image: "alchemy_lab/beryllium_alchemy_lab.webp",
    modifying: {
      building: "Alchemy Lab",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Alchemy Lab",
      amount: 5,
    },
    tier: "beryllium",
    owned: false,
  },
  {
    name: "True chocolate",
    description: "Alchemy labs are twice as efficient.",
    price: 37.5e12,
    image: "alchemy_lab/blueberyllium_alchemy_lab.webp",
    modifying: {
      building: "Alchemy Lab",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Alchemy Lab",
      amount: 25,
    },
    tier: "blueberyllium",
    owned: false,
  },
  {
    name: "Ambrosia",
    description: "Alchemy labs are twice as efficient.",
    price: 3.75e15,
    image: "alchemy_lab/chalcedhoney_alchemy_lab.webp",
    modifying: {
      building: "Alchemy Lab",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Alchemy Lab",
      amount: 50,
    },
    tier: "chalcedhoney",
    owned: false,
  },
  {
    name: "Aqua crustulae",
    description: "Alchemy labs are twice as efficient.",
    price: 375e15,
    image: "alchemy_lab/buttergold_alchemy_lab.webp",
    modifying: {
      building: "Alchemy Lab",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Alchemy Lab",
      amount: 100,
    },
    tier: "buttergold",
    owned: false,
  },
  {
    name: "Origin crucible",
    description: "Alchemy labs are twice as efficient.",
    price: 37.5e18,
    image: "alchemy_lab/sugarmuck_alchemy_lab.webp",
    modifying: {
      building: "Alchemy Lab",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Alchemy Lab",
      amount: 150,
    },
    tier: "sugarmuck",
    owned: false,
  },
  {
    name: "Theory of atomic fluidity",
    description: "Alchemy labs are twice as efficient.",
    price: 37.5e21,
    image: "alchemy_lab/jetmint_alchemy_lab.webp",
    modifying: {
      building: "Alchemy Lab",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Alchemy Lab",
      amount: 200,
    },
    tier: "jetmint",
    owned: false,
  },
  {
    name: "Beige goo",
    description: "Alchemy labs are twice as efficient.",
    price: 37.5e24,
    image: "alchemy_lab/cherrysilver_alchemy_lab.webp",
    modifying: {
      building: "Alchemy Lab",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Alchemy Lab",
      amount: 250,
    },
    tier: "cherrysilver",
    owned: false,
  },
  {
    name: "The advent of chemistry",
    description: "Alchemy labs are twice as efficient.",
    price: 37.5e27,
    image: "alchemy_lab/hazelrald_alchemy_lab.webp",
    modifying: {
      building: "Alchemy Lab",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Alchemy Lab",
      amount: 300,
    },
    tier: "hazelrald",
    owned: false,
  },
  {
    name: "On second thought",
    description: "Alchemy labs are twice as efficient.",
    price: 37.5e30,
    image: "alchemy_lab/mooncandy_alchemy_lab.webp",
    modifying: {
      building: "Alchemy Lab",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Alchemy Lab",
      amount: 350,
    },
    tier: "mooncandy",
    owned: false,
  },
  {
    name: "Public betterment",
    description: "Alchemy labs are twice as efficient.",
    price: 375e33,
    image: "alchemy_lab/astrofudge_alchemy_lab.webp",
    modifying: {
      building: "Alchemy Lab",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Alchemy Lab",
      amount: 400,
    },
    tier: "astrofudge",
    owned: false,
  },
  {
    name: "Hermetic reconciliation",
    description: "Alchemy labs are twice as efficient.",
    price: 3.75e39,
    image: "alchemy_lab/alabascream_alchemy_lab.webp",
    modifying: {
      building: "Alchemy Lab",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Alchemy Lab",
      amount: 450,
    },
    tier: "alabascream",
    owned: false,
  },
  {
    name: "Chomatic cycling",
    description: "Alchemy labs are twice as efficient.",
    price: 37.5e42,
    image: "alchemy_lab/iridyum_alchemy_lab.webp",
    modifying: {
      building: "Alchemy Lab",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Alchemy Lab",
      amount: 500,
    },
    tier: "iridyum",
    owned: false,
  },
  {
    name: "Arcanized glassware",
    description: "Alchemy labs are twice as efficient.",
    price: 375e45,
    image: "alchemy_lab/glucosmium_alchemy_lab.webp",
    modifying: {
      building: "Alchemy Lab",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Alchemy Lab",
      amount: 550,
    },
    tier: "glucosmium",
    owned: false,
  },
  {
    name: "The dose makes the poison",
    description: "Alchemy labs are twice as efficient.",
    price: 3.75e51,
    image: "alchemy_lab/glimmeringue_alchemy_lab.webp",
    modifying: {
      building: "Alchemy Lab",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Alchemy Lab",
      amount: 600,
    },
    tier: "glimmeringue",
    owned: false,
  },
]