export const AntimatterCondenserUpgrades = [
  {
    name: "Sugar bosons",
    description: "Antimatter condensers are twice as efficient.",
    price: 1.7e15,
    image: "plain_antimatter_condenser.webp",
    modifying: {
      building: "Antimatter Condenser",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Antimatter Condenser",
      amount: 1,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "String theory",
    description: "Antimatter condensers are twice as efficient.",
    price: 8.5e15,
    image: "beryllium_antimatter_condenser.webp",
    modifying: {
      building: "Antimatter Condenser",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Antimatter Condenser",
      amount: 5,
    },
    tier: "beryllium",
    owned: false,
  },
  {
    name: "Large macaron collider",
    description: "Antimatter condensers are twice as efficient.",
    price: 85e15,
    image: "blueberyllium_antimatter_condenser.webp",
    modifying: {
      building: "Antimatter Condenser",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Antimatter Condenser",
      amount: 25,
    },
    tier: "blueberyllium",
    owned: false,
  },
  {
    name: "Big bang bake",
    description: "Antimatter condensers are twice as efficient.",
    price: 8.5e18,
    image: "chalcedhoney_antimatter_condenser.webp",
    modifying: {
      building: "Antimatter Condenser",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Antimatter Condenser",
      amount: 50,
    },
    tier: "chalcedhoney",
    owned: false,
  },
  {
    name: "Reverse cyclotrons",
    description: "Antimatter condensers are twice as efficient.",
    price: 850e18,
    image: "buttergold_antimatter_condenser.webp",
    modifying: {
      building: "Antimatter Condenser",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Antimatter Condenser",
      amount: 100,
    },
    tier: "buttergold",
    owned: false,
  },
  {
    name: "Nanocosmics",
    description: "Antimatter condensers are twice as efficient.",
    price: 85e21,
    image: "sugarmuck_antimatter_condenser.webp",
    modifying: {
      building: "Antimatter Condenser",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Antimatter Condenser",
      amount: 150,
    },
    tier: "sugarmuck",
    owned: false,
  },
  {
    name: "The Pulse",
    description: "Antimatter condensers are twice as efficient.",
    price: 85e24,
    image: "jetmint_antimatter_condenser.webp",
    modifying: {
      building: "Antimatter Condenser",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Antimatter Condenser",
      amount: 200,
    },
    tier: "jetmint",
    owned: false,
  },
  {
    name: "Some other super-tiny fundamental particle? Probably?",
    description: "Antimatter condensers are twice as efficient.",
    price: 85e27,
    image: "cherrysilver_antimatter_condenser.webp",
    modifying: {
      building: "Antimatter Condenser",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Antimatter Condenser",
      amount: 250,
    },
    tier: "cherrysilver",
    owned: false,
  },
  {
    name: "Quantum comb",
    description: "Antimatter condensers are twice as efficient.",
    price: 85e30,
    image: "hazelrald_antimatter_condenser.webp",
    modifying: {
      building: "Antimatter Condenser",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Antimatter Condenser",
      amount: 300,
    },
    tier: "hazelrald",
    owned: false,
  },
  {
    name: "Baking Nobel prize",
    description: "Antimatter condensers are twice as efficient.",
    price: 85e33,
    image: "mooncandy_antimatter_condenser.webp",
    modifying: {
      building: "Antimatter Condenser",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Antimatter Condenser",
      amount: 350,
    },
    tier: "mooncandy",
    owned: false,
  },
  {
    name: "The definite molecule",
    description: "Antimatter condensers are twice as efficient.",
    price: 850e36,
    image: "astrofudge_antimatter_condenser.webp",
    modifying: {
      building: "Antimatter Condenser",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Antimatter Condenser",
      amount: 400,
    },
    tier: "astrofudge",
    owned: false,
  },
  {
    name: "Flavor itself",
    description: "Antimatter condensers are twice as efficient.",
    price: 8.5e42,
    image: "alabascream_antimatter_condenser.webp",
    modifying: {
      building: "Antimatter Condenser",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Antimatter Condenser",
      amount: 450,
    },
    tier: "alabascream",
    owned: false,
  },
  {
    name: "Delicious pull",
    description: "Antimatter condensers are twice as efficient.",
    price: 85e45,
    image: "iridyum_antimatter_condenser.webp",
    modifying: {
      building: "Antimatter Condenser",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Antimatter Condenser",
      amount: 500,
    },
    tier: "iridyum",
    owned: false,
  },
  {
    name: "Employee minification",
    description: "Antimatter condensers are twice as efficient.",
    price: 850e48,
    image: "glucosmium_antimatter_condenser.webp",
    modifying: {
      building: "Antimatter Condenser",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Antimatter Condenser",
      amount: 550,
    },
    tier: "glucosmium",
    owned: false,
  },
  {
    name: "Candied atoms",
    description: "Antimatter condensers are twice as efficient.",
    price: 8.5e54,
    image: "glimmeringue_antimatter_condenser.webp",
    modifying: {
      building: "Antimatter Condenser",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Antimatter Condenser",
      amount: 600,
    },
    tier: "glimmeringue",
    owned: false,
  },
]