export const BankUpgrades = [
  {
    name: "Taller tellers",
    description: "Banks are twice as efficient.",
    price: 14e6,
    image: "plain_bank.webp",
    modifying: {
      building: "Bank",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Bank",
      amount: 1,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "Scissor-resistant credit cards",
    description: "Banks are twice as efficient.",
    price: 70e6,
    image: "beryllium_bank.webp",
    modifying: {
      building: "Bank",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Bank",
      amount: 5,
    },
    tier: "beryllium",
    owned: false,
  },
  {
    name: "Acid-proof vaults",
    description: "Banks are twice as efficient.",
    price: 700e6,
    image: "blueberyllium_bank.webp",
    modifying: {
      building: "Bank",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Bank",
      amount: 25,
    },
    tier: "blueberyllium",
    owned: false,
  },
  {
    name: "Chocolate coins",
    description: "Banks are twice as efficient.",
    price: 70e9,
    image: "chalcedhoney_bank.webp",
    modifying: {
      building: "Bank",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Bank",
      amount: 50,
    },
    tier: "chalcedhoney",
    owned: false,
  },
  {
    name: "Exponential interest rates",
    description: "Banks are twice as efficient.",
    price: 7e12,
    image: "buttergold_bank.webp",
    modifying: {
      building: "Bank",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Bank",
      amount: 100,
    },
    tier: "buttergold",
    owned: false,
  },
  {
    name: "Financial zen",
    description: "Banks are twice as efficient.",
    price: 700e12,
    image: "sugarmuck_bank.webp",
    modifying: {
      building: "Bank",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Bank",
      amount: 150,
    },
    tier: "sugarmuck",
    owned: false,
  },
  {
    name: "Way of the wallet",
    description: "Banks are twice as efficient.",
    price: 700e15,
    image: "jetmint_bank.webp",
    modifying: {
      building: "Bank",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Bank",
      amount: 200,
    },
    tier: "jetmint",
    owned: false,
  },
  {
    name: "The stuff rationale",
    description: "Banks are twice as efficient.",
    price: 700e18,
    image: "cherrysilver_bank.webp",
    modifying: {
      building: "Bank",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Bank",
      amount: 250,
    },
    tier: "cherrysilver",
    owned: false,
  },
  {
    name: "Edible money",
    description: "Banks are twice as efficient.",
    price: 700e21,
    image: "hazelrald_bank.webp",
    modifying: {
      building: "Bank",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Bank",
      amount: 300,
    },
    tier: "hazelrald",
    owned: false,
  },
  {
    name: "Grand supercycle",
    description: "Banks are twice as efficient.",
    price: 700e24,
    image: "mooncandy_bank.webp",
    modifying: {
      building: "Bank",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Bank",
      amount: 350,
    },
    tier: "mooncandy",
    owned: false,
  },
  {
    name: "Rules of acquisition",
    description: "Banks are twice as efficient.",
    price: 7e30,
    image: "astrofudge_bank.webp",
    modifying: {
      building: "Bank",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Bank",
      amount: 400,
    },
    tier: "astrofudge",
    owned: false,
  },
  {
    name: "Altruistic loop",
    description: "Banks are twice as efficient.",
    price: 70e33,
    image: "alabascream_bank.webp",
    modifying: {
      building: "Bank",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Bank",
      amount: 450,
    },
    tier: "alabascream",
    owned: false,
  },
  {
    name: "Diminishing tax returns",
    description: "Banks are twice as efficient.",
    price: 700e36,
    image: "iridyum_bank.webp",
    modifying: {
      building: "Bank",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Bank",
      amount: 500,
    },
    tier: "iridyum",
    owned: false,
  },
  {
    name: "Cookie Points",
    description: "Banks are twice as efficient.",
    price: 7e42,
    image: "glucosmium_bank.webp",
    modifying: {
      building: "Bank",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Bank",
      amount: 550,
    },
    tier: "glucosmium",
    owned: false,
  },
  {
    name: "The big shortcake",
    description: "Banks are twice as efficient.",
    price: 70e45,
    image: "glimmeringue_bank.webp",
    modifying: {
      building: "Bank",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Bank",
      amount: 600,
    },
    tier: "glimmeringue",
    owned: false,
  },
]