export const ChancemakerUpgrades = [
  {
    name: "Your lucky cookie",
    description: "Chancemakers are twice as efficient.",
    price: 260e15,
    image: "plain_chancemaker.webp",
    modifying: {
      building: "Chancemaker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Chancemaker",
      amount: 1,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: '"All bets are Off" magic coin',
    description: "Chancemakers are twice as efficient.",
    price: 1.3e18,
    image: "beryllium_chancemaker.webp",
    modifying: {
      building: "Chancemaker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Chancemaker",
      amount: 5,
    },
    tier: "beryllium",
    owned: false,
  },
  {
    name: "Winning lottery ticket",
    description: "Chancemakers are twice as efficient.",
    price: 13e18,
    image: "blueberyllium_chancemaker.webp",
    modifying: {
      building: "Chancemaker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Chancemaker",
      amount: 25,
    },
    tier: "blueberyllium",
    owned: false,
  },
  {
    name: "Four-leaf clover field",
    description: "Chancemakers are twice as efficient.",
    price: 1.3e21,
    image: "chalcedhoney_chancemaker.webp",
    modifying: {
      building: "Chancemaker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Chancemaker",
      amount: 50,
    },
    tier: "chalcedhoney",
    owned: false,
  },
  {
    name: "A recipe book about books",
    description: "Chancemakers are twice as efficient.",
    price: 130e21,
    image: "buttergold_chancemaker.webp",
    modifying: {
      building: "Chancemaker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Chancemaker",
      amount: 100,
    },
    tier: "buttergold",
    owned: false,
  },
  {
    name: "Leprechaun village",
    description: "Chancemakers are twice as efficient.",
    price: 13e24,
    image: "sugarmuck_chancemaker.webp",
    modifying: {
      building: "Chancemaker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Chancemaker",
      amount: 150,
    },
    tier: "sugarmuck",
    owned: false,
  },
  {
    name: "Improbability drive",
    description: "Chancemakers are twice as efficient.",
    price: 13e27,
    image: "jetmint_chancemaker.webp",
    modifying: {
      building: "Chancemaker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Chancemaker",
      amount: 200,
    },
    tier: "jetmint",
    owned: false,
  },
  {
    name: "Antisuperstistronics",
    description: "Chancemakers are twice as efficient.",
    price: 13e30,
    image: "cherrysilver_chancemaker.webp",
    modifying: {
      building: "Chancemaker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Chancemaker",
      amount: 250,
    },
    tier: "cherrysilver",
    owned: false,
  },
  {
    name: "Bunnypedes",
    description: "Chancemakers are twice as efficient.",
    price: 13e33,
    image: "hazelrald_chancemaker.webp",
    modifying: {
      building: "Chancemaker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Chancemaker",
      amount: 300,
    },
    tier: "hazelrald",
    owned: false,
  },
  {
    name: "Revised probabilistics",
    description: "Chancemakers are twice as efficient.",
    price: 13e36,
    image: "mooncandy_chancemaker.webp",
    modifying: {
      building: "Chancemaker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Chancemaker",
      amount: 350,
    },
    tier: "mooncandy",
    owned: false,
  },
  {
    name: "0-sided dice",
    description: "Chancemakers are twice as efficient.",
    price: 130e39,
    image: "astrofudge_chancemaker.webp",
    modifying: {
      building: "Chancemaker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Chancemaker",
      amount: 400,
    },
    tier: "astrofudge",
    owned: false,
  },
  {
    name: "A touch of determinism",
    description: "Chancemakers are twice as efficient.",
    price: 1.3e45,
    image: "alabascream_chancemaker.webp",
    modifying: {
      building: "Chancemaker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Chancemaker",
      amount: 450,
    },
    tier: "alabascream",
    owned: false,
  },
  {
    name: "On a streak",
    description: "Chancemakers are twice as efficient.",
    price: 13e48,
    image: "iridyum_chancemaker.webp",
    modifying: {
      building: "Chancemaker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Chancemaker",
      amount: 500,
    },
    tier: "iridyum",
    owned: false,
  },
  {
    name: "Silver lining maximization",
    description: "Chancemakers are twice as efficient.",
    price: 130e51,
    image: "glucosmium_chancemaker.webp",
    modifying: {
      building: "Chancemaker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Chancemaker",
      amount: 550,
    },
    tier: "glucosmium",
    owned: false,
  },
  {
    name: "Gambler's fallacy fallacy",
    description: "Chancemakers are twice as efficient.",
    price: 1.3e57,
    image: "glimmeringue_chancemaker.webp",
    modifying: {
      building: "Chancemaker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Chancemaker",
      amount: 600,
    },
    tier: "glimmeringue",
    owned: false,
  },
]