export const CortexBakerUpgrades = [
  {
    name: "Principled neural shackles",
    description: "Cortex bakers are twice as efficient.",
    price: 19e24,
    image: "plain_cortex_baker.webp",
    modifying: {
      building: "Cortex Baker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Cortex Baker",
      amount: 1,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "Obey",
    description: "Cortex bakers are twice as efficient.",
    price: 95e24,
    image: "beryllium_cortex_baker.webp",
    modifying: {
      building: "Cortex Baker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Cortex Baker",
      amount: 5,
    },
    tier: "beryllium",
    owned: false,
  },
  {
    name: "A sprinkle of irrationality",
    description: "Cortex bakers are twice as efficient.",
    price: 950e24,
    image: "blueberyllium_cortex_baker.webp",
    modifying: {
      building: "Cortex Baker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Cortex Baker",
      amount: 25,
    },
    tier: "blueberyllium",
    owned: false,
  },
  {
    name: "Front and back hemispheres",
    description: "Cortex bakers are twice as efficient.",
    price: 95e27,
    image: "chalcedhoney_cortex_baker.webp",
    modifying: {
      building: "Cortex Baker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Cortex Baker",
      amount: 50,
    },
    tier: "chalcedhoney",
    owned: false,
  },
  {
    name: "Neural networking",
    description: "Cortex bakers are twice as efficient.",
    price: 9.5e30,
    image: "buttergold_cortex_baker.webp",
    modifying: {
      building: "Cortex Baker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Cortex Baker",
      amount: 100,
    },
    tier: "buttergold",
    owned: false,
  },
  {
    name: "Cosmic brainstorms",
    description: "Cortex bakers are twice as efficient.",
    price: 950e30,
    image: "sugarmuck_cortex_baker.webp",
    modifying: {
      building: "Cortex Baker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Cortex Baker",
      amount: 150,
    },
    tier: "sugarmuck",
    owned: false,
  },
  {
    name: "Megatherapy",
    description: "Cortex bakers are twice as efficient.",
    price: 950e33,
    image: "jetmint_cortex_baker.webp",
    modifying: {
      building: "Cortex Baker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Cortex Baker",
      amount: 200,
    },
    tier: "jetmint",
    owned: false,
  },
  {
    name: "Synaptic lubricant",
    description: "Cortex bakers are twice as efficient.",
    price: 950e36,
    image: "cherrysilver_cortex_baker.webp",
    modifying: {
      building: "Cortex Baker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Cortex Baker",
      amount: 250,
    },
    tier: "cherrysilver",
    owned: false,
  },
  {
    name: "Psychokinesis",
    description: "Cortex bakers are twice as efficient.",
    price: 950e39,
    image: "hazelrald_cortex_baker.webp",
    modifying: {
      building: "Cortex Baker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Cortex Baker",
      amount: 300,
    },
    tier: "hazelrald",
    owned: false,
  },
  {
    name: "Spines",
    description: "Cortex bakers are twice as efficient.",
    price: 950e42,
    image: "mooncandy_cortex_baker.webp",
    modifying: {
      building: "Cortex Baker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Cortex Baker",
      amount: 350,
    },
    tier: "mooncandy",
    owned: false,
  },
  {
    name: "Neuraforming",
    description: "Cortex bakers are twice as efficient.",
    price: 9.5e48,
    image: "astrofudge_cortex_baker.webp",
    modifying: {
      building: "Cortex Baker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Cortex Baker",
      amount: 400,
    },
    tier: "astrofudge",
    owned: false,
  },
  {
    name: "Epistemological trickery",
    description: "Cortex bakers are twice as efficient.",
    price: 95e51,
    image: "alabascream_cortex_baker.webp",
    modifying: {
      building: "Cortex Baker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Cortex Baker",
      amount: 450,
    },
    tier: "alabascream",
    owned: false,
  },
  {
    name: "Every possible idea",
    description: "Cortex bakers are twice as efficient.",
    price: 950e54,
    image: "iridyum_cortex_baker.webp",
    modifying: {
      building: "Cortex Baker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Cortex Baker",
      amount: 500,
    },
    tier: "iridyum",
    owned: false,
  },
  {
    name: "The land of dreams",
    description: "Cortex bakers are twice as efficient.",
    price: 9.5e60,
    image: "glucosmium_cortex_baker.webp",
    modifying: {
      building: "Cortex Baker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Cortex Baker",
      amount: 550,
    },
    tier: "glucosmium",
    owned: false,
  },
  {
    name: "Intellectual property theft",
    description: "Cortex bakers are twice as efficient.",
    price: 95e63,
    image: "glimmeringue_cortex_baker.webp",
    modifying: {
      building: "Cortex Baker",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Cortex Baker",
      amount: 600,
    },
    tier: "glimmeringue",
    owned: false,
  },
]