export const CortexBakerUpgrades = [
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "plain_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 1,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "plain_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 5,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "plain_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 25,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "plain_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 50,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "plain_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 100,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "plain_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 150,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "plain_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 200,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "plain_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 250,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "plain_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 300,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "plain_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 350,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "plain_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 400,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "plain_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 450,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "plain_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 500,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "plain_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 550,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "plain_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 600,
    },
    tier: "plain",
    owned: false,
  },
]