export const FactoryUpgrades = [
  {
    name: "Sturdier conveyor belts",
    description: "Factories are twice as efficient.",
    price: 1.3e6,
    image: "factory/plain_factory.webp",
    modifying: {
      building: "Factory",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Factory",
      amount: 1,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "Child labor",
    description: "Factories are twice as efficient.",
    price: 6.5e6,
    image: "factory/beryllium_factory.webp",
    modifying: {
      building: "Factory",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Factory",
      amount: 5,
    },
    tier: "beryllium",
    owned: false,
  },
  {
    name: "Sweatshop",
    description: "Factories are twice as efficient.",
    price: 65e6,
    image: "factory/blueberyllium_factory.webp",
    modifying: {
      building: "Factory",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Factory",
      amount: 25,
    },
    tier: "blueberyllium",
    owned: false,
  },
  {
    name: "Radium reactors",
    description: "Factories are twice as efficient.",
    price: 6.5e9,
    image: "factory/chalcedhoney_factory.webp",
    modifying: {
      building: "Factory",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Factory",
      amount: 50,
    },
    tier: "chalcedhoney",
    owned: false,
  },
  {
    name: "Recombobulators",
    description: "Factories are twice as efficient.",
    price: 650e9,
    image: "factory/buttergold_factory.webp",
    modifying: {
      building: "Factory",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Factory",
      amount: 100,
    },
    tier: "buttergold",
    owned: false,
  },
  {
    name: "Deep-bake process",
    description: "Factories are twice as efficient.",
    price: 65e12,
    image: "factory/sugarmuck_factory.webp",
    modifying: {
      building: "Factory",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Factory",
      amount: 150,
    },
    tier: "sugarmuck",
    owned: false,
  },
  {
    name: "Cyborg workforce",
    description: "Factories are twice as efficient.",
    price: 65e15,
    image: "factory/jetmint_factory.webp",
    modifying: {
      building: "Factory",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Factory",
      amount: 200,
    },
    tier: "jetmint",
    owned: false,
  },
  {
    name: "78-hour days",
    description: "Factories are twice as efficient.",
    price: 65e18,
    image: "factory/cherrysilver_factory.webp",
    modifying: {
      building: "Factory",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Factory",
      amount: 250,
    },
    tier: "cherrysilver",
    owned: false,
  },
  {
    name: "Machine learning",
    description: "Factories are twice as efficient.",
    price: 65e21,
    image: "factory/hazelrald_factory.webp",
    modifying: {
      building: "Factory",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Factory",
      amount: 300,
    },
    tier: "hazelrald",
    owned: false,
  },
  {
    name: "Brownie point system",
    description: "Factories are twice as efficient.",
    price: 65e24,
    image: "factory/mooncandy_factory.webp",
    modifying: {
      building: "Factory",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Factory",
      amount: 350,
    },
    tier: "mooncandy",
    owned: false,
  },
  {
    name: '"Volunteer" interns',
    description: "Factories are twice as efficient.",
    price: 650e27,
    image: "factory/astrofudge_factory.webp",
    modifying: {
      building: "Factory",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Factory",
      amount: 400,
    },
    tier: "astrofudge",
    owned: false,
  },
  {
    name: "Behavioral refarming",
    description: "Factories are twice as efficient.",
    price: 6.5e33,
    image: "factory/alabascream_factory.webp",
    modifying: {
      building: "Factory",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Factory",
      amount: 450,
    },
    tier: "alabascream",
    owned: false,
  },
  {
    name: "The infinity engine",
    description: "Factories are twice as efficient.",
    price: 65e36,
    image: "factory/iridyum_factory.webp",
    modifying: {
      building: "Factory",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Factory",
      amount: 500,
    },
    tier: "iridyum",
    owned: false,
  },
  {
    name: "N-dimensional assembly lines",
    description: "Factories are twice as efficient.",
    price: 650e39,
    image: "factory/glucosmium_factory.webp",
    modifying: {
      building: "Factory",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Factory",
      amount: 550,
    },
    tier: "glucosmium",
    owned: false,
  },
  {
    name: "Universal automation",
    description: "Factories are twice as efficient.",
    price: 6.5e45,
    image: "factory/glimmeringue_factory.webp",
    modifying: {
      building: "Factory",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Factory",
      amount: 600,
    },
    tier: "glimmeringue",
    owned: false,
  },
]