export const FarmUpgrades = [
  {
    name: "Cheap hoes",
    description: "Farms are twice as efficient.",
    price: 11e3,
    image: "plain_farm.webp",
    modifying: {
      building: "Farm",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Farm",
      amount: 1,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "Fertilizer",
    description: "Farms are twice as efficient.",
    price: 55e3,
    image: "beryllium_farm.webp",
    modifying: {
      building: "Farm",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Farm",
      amount: 5,
    },
    tier: "beryllium",
    owned: false,
  },
  {
    name: "Cookie trees",
    description: "Farms are twice as efficient.",
    price: 550e3,
    image: "blueberyllium_farm.webp",
    modifying: {
      building: "Farm",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Farm",
      amount: 25,
    },
    tier: "blueberyllium",
    owned: false,
  },
  {
    name: "Genetically-modified cookies",
    description: "Farms are twice as efficient.",
    price: 55e6,
    image: "chalcedhoney_farm.webp",
    modifying: {
      building: "Farm",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Farm",
      amount: 50,
    },
    tier: "chalcedhoney",
    owned: false,
  },
  {
    name: "Gingerbread scarecrows",
    description: "Farms are twice as efficient.",
    price: 5.5e9,
    image: "buttergold_farm.webp",
    modifying: {
      building: "Farm",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Farm",
      amount: 100,
    },
    tier: "buttergold",
    owned: false,
  },
  {
    name: "Pulsar sprinklers",
    description: "Farms are twice as efficient.",
    price: 550e9,
    image: "sugarmuck_farm.webp",
    modifying: {
      building: "Farm",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Farm",
      amount: 150,
    },
    tier: "sugarmuck",
    owned: false,
  },
  {
    name: "Fudge fungus",
    description: "Farms are twice as efficient.",
    price: 550e12,
    image: "jetmint_farm.webp",
    modifying: {
      building: "Farm",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Farm",
      amount: 200,
    },
    tier: "jetmint",
    owned: false,
  },
  {
    name: "Wheat triffids",
    description: "Farms are twice as efficient.",
    price: 550e15,
    image: "cherrysilver_farm.webp",
    modifying: {
      building: "Farm",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Farm",
      amount: 250,
    },
    tier: "cherrysilver",
    owned: false,
  },
  {
    name: "Humane pesticides",
    description: "Farms are twice as efficient.",
    price: 550e18,
    image: "hazelrald_farm.webp",
    modifying: {
      building: "Farm",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Farm",
      amount: 300,
    },
    tier: "hazelrald",
    owned: false,
  },
  {
    name: "Barnstars",
    description: "Farms are twice as efficient.",
    price: 550e21,
    image: "mooncandy_farm.webp",
    modifying: {
      building: "Farm",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Farm",
      amount: 350,
    },
    tier: "mooncandy",
    owned: false,
  },
  {
    name: "Lindworms",
    description: "Farms are twice as efficient.",
    price: 5.5e27,
    image: "astrofudge_farm.webp",
    modifying: {
      building: "Farm",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Farm",
      amount: 400,
    },
    tier: "astrofudge",
    owned: false,
  },
  {
    name: "Global seed vault",
    description: "Farms are twice as efficient.",
    price: 55e30,
    image: "alabascream_farm.webp",
    modifying: {
      building: "Farm",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Farm",
      amount: 450,
    },
    tier: "alabascream",
    owned: false,
  },
  {
    name: "Reverse-veganism",
    description: "Farms are twice as efficient.",
    price: 550e33,
    image: "iridyum_farm.webp",
    modifying: {
      building: "Farm",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Farm",
      amount: 500,
    },
    tier: "iridyum",
    owned: false,
  },
  {
    name: "Cookie mulch",
    description: "Farms are twice as efficient.",
    price: 5.5e39,
    image: "glucosmium_farm.webp",
    modifying: {
      building: "Farm",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Farm",
      amount: 250,
    },
    tier: "glucosmium",
    owned: false,
  },
  {
    name: "Self-driving tractors",
    description: "Farms are twice as efficient.",
    price: 55e42,
    image: "glimmeringue_farm.webp",
    modifying: {
      building: "Farm",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Farm",
      amount: 250,
    },
    tier: "glimmeringue",
    owned: false,
  },
]