export const FractalEngineUpgrades = [
  {
    name: "Metabakeries",
    description: "Fractal engines twice as efficient.",
    price: 3.1e18,
    image: "fractal_engine/plain_fractal_engine.webp",
    modifying: {
      building: "Fractal Engine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Fractal Engine",
      amount: 1,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "Mendelbrown sugar",
    description: "Fractal engines twice as efficient.",
    price: 15.5e18,
    image: "fractal_engine/beryllium_fractal_engine.webp",
    modifying: {
      building: "Fractal Engine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Fractal Engine",
      amount: 5,
    },
    tier: "beryllium",
    owned: false,
  },
  {
    name: "Fractoids",
    description: "Fractal engines twice as efficient.",
    price: 155e18,
    image: "fractal_engine/blueberyllium_fractal_engine.webp",
    modifying: {
      building: "Fractal Engine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Fractal Engine",
      amount: 25,
    },
    tier: "blueberyllium",
    owned: false,
  },
  {
    name: "Nested universe theory",
    description: "Fractal engines twice as efficient.",
    price: 15.5e21,
    image: "fractal_engine/chalcedhoney_fractal_engine.webp",
    modifying: {
      building: "Fractal Engine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Fractal Engine",
      amount: 50,
    },
    tier: "chalcedhoney",
    owned: false,
  },
  {
    name: "Menger sponge cake",
    description: "Fractal engines twice as efficient.",
    price: 1.55e24,
    image: "fractal_engine/buttergold_fractal_engine.webp",
    modifying: {
      building: "Fractal Engine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Fractal Engine",
      amount: 100,
    },
    tier: "buttergold",
    owned: false,
  },
  {
    name: "One particularly good-humored cow",
    description: "Fractal engines twice as efficient.",
    price: 155e24,
    image: "fractal_engine/sugarmuck_fractal_engine.webp",
    modifying: {
      building: "Fractal Engine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Fractal Engine",
      amount: 150,
    },
    tier: "sugarmuck",
    owned: false,
  },
  {
    name: "Chocolate ouroboros",
    description: "Fractal engines twice as efficient.",
    price: 155e27,
    image: "fractal_engine/jetmint_fractal_engine.webp",
    modifying: {
      building: "Fractal Engine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Fractal Engine",
      amount: 200,
    },
    tier: "jetmint",
    owned: false,
  },
  {
    name: "Nested",
    description: "Fractal engines twice as efficient.",
    price: 155e30,
    image: "fractal_engine/cherrysilver_fractal_engine.webp",
    modifying: {
      building: "Fractal Engine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Fractal Engine",
      amount: 250,
    },
    tier: "cherrysilver",
    owned: false,
  },
  {
    name: "Space-filling fibers",
    description: "Fractal engines twice as efficient.",
    price: 155e33,
    image: "fractal_engine/hazelrald_fractal_engine.webp",
    modifying: {
      building: "Fractal Engine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Fractal Engine",
      amount: 300,
    },
    tier: "hazelrald",
    owned: false,
  },
  {
    name: "Endless book of prose",
    description: "Fractal engines twice as efficient.",
    price: 155e36,
    image: "fractal_engine/mooncandy_fractal_engine.webp",
    modifying: {
      building: "Fractal Engine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Fractal Engine",
      amount: 350,
    },
    tier: "mooncandy",
    owned: false,
  },
  {
    name: "The set of all sets",
    description: "Fractal engines twice as efficient.",
    price: 1.55e42,
    image: "fractal_engine/astrofudge_fractal_engine.webp",
    modifying: {
      building: "Fractal Engine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Fractal Engine",
      amount: 400,
    },
    tier: "astrofudge",
    owned: false,
  },
  {
    name: "This upgrade",
    description: "Fractal engines twice as efficient.",
    price: 15e45,
    image: "fractal_engine/alabascream_fractal_engine.webp",
    modifying: {
      building: "Fractal Engine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Fractal Engine",
      amount: 450,
    },
    tier: "alabascream",
    owned: false,
  },
  {
    name: "A box",
    description: "Fractal engines twice as efficient.",
    price: 155e48,
    image: "fractal_engine/iridyum_fractal_engine.webp",
    modifying: {
      building: "Fractal Engine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Fractal Engine",
      amount: 500,
    },
    tier: "iridyum",
    owned: false,
  },
  {
    name: "Multiscale profiling",
    description: "Fractal engines twice as efficient.",
    price: 1.55e54,
    image: "fractal_engine/glucosmium_fractal_engine.webp",
    modifying: {
      building: "Fractal Engine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Fractal Engine",
      amount: 550,
    },
    tier: "glucosmium",
    owned: false,
  },
  {
    name: "The more they stay the same",
    description: "Fractal engines twice as efficient.",
    price: 15.5e57,
    image: "fractal_engine/glimmeringue_fractal_engine.webp",
    modifying: {
      building: "Fractal Engine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Fractal Engine",
      amount: 600,
    },
    tier: "glimmeringue",
    owned: false,
  },
]