export const GrandmaUpgrades = [
  {
    name: "Forwards from grandma",
    description: "Grandmas are twice as efficient.",
    price: 1e3,
    image: "plain_grandma.webp",
    modifying: {
      building: "Grandma",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Grandma",
      amount: 1,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "Steel-plated rolling pins",
    description: "Grandmas are twice as efficient.",
    price: 5e3,
    image: "beryllium_grandma.webp",
    modifying: {
      building: "Grandma",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Grandma",
      amount: 5,
    },
    tier: "beryllium",
    owned: false,
  },
  {
    name: "Lubricated dentures",
    description: "Grandmas are twice as efficient.",
    price: 5e4,
    image: "blueberyllium_grandma.webp",
    modifying: {
      building: "Grandma",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Grandma",
      amount: 25,
    },
    tier: "blueberyllium",
    owned: false,
  },
  {
    name: "Prune juice",
    description: "Grandmas are twice as efficient.",
    price: 5e6,
    image: "chalcedhoney_grandma.webp",
    modifying: {
      building: "Grandma",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Grandma",
      amount: 50,
    },
    tier: "chalcedhoney",
    owned: false,
  },
  {
    name: "Double tick glasses",
    description: "Grandmas are twice as efficient.",
    price: 5e8,
    image: "buttergold_grandma.webp",
    modifying: {
      building: "Grandma",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Grandma",
      amount: 100,
    },
    tier: "buttergold",
    owned: false,
  },
  {
    name: "Aging agents",
    description: "Grandmas are twice as efficient.",
    price: 5e10,
    image: "sugarmuck_grandma.webp",
    modifying: {
      building: "Grandma",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Grandma",
      amount: 150,
    },
    tier: "sugarmuck",
    owned: false,
  },
  {
    name: "Xtreme walkers",
    description: "Grandmas are twice as efficient.",
    price: 5e13,
    image: "jetmint_grandma.webp",
    modifying: {
      building: "Grandma",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Grandma",
      amount: 200,
    },
    tier: "jetmint",
    owned: false,
  },
  {
    name: "The Unbridling",
    description: "Grandmas are twice as efficient.",
    price: 5e16,
    image: "cherrysilver_grandma.webp",
    modifying: {
      building: "Grandma",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Grandma",
      amount: 250,
    },
    tier: "cherrysilver",
    owned: false,
  },
  {
    name: "Reverse dementia",
    description: "Grandmas are twice as efficient.",
    price: 5e19,
    image: "hazelrald_grandma.webp",
    modifying: {
      building: "Grandma",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Grandma",
      amount: 300,
    },
    tier: "hazelrald",
    owned: false,
  },
  {
    name: "Timeproof hair dyes",
    description: "Grandmas are twice as efficient.",
    price: 5e22,
    image: "mooncandy_grandma.webp",
    modifying: {
      building: "Grandma",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Grandma",
      amount: 350,
    },
    tier: "mooncandy",
    owned: false,
  },
  {
    name: "Good manners",
    description: "Grandmas are twice as efficient.",
    price: 5e26,
    image: "astrofudge_grandma.webp",
    modifying: {
      building: "Grandma",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Grandma",
      amount: 400,
    },
    tier: "astrofudge",
    owned: false,
  },
  {
    name: "Generation degeneration",
    description: "Grandmas are twice as efficient.",
    price: 5e30,
    image: "alabascream_grandma.webp",
    modifying: {
      building: "Grandma",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Grandma",
      amount: 450,
    },
    tier: "alabascream",
    owned: false,
  },
  {
    name: "Visits",
    description: "Grandmas are twice as efficient.",
    price: 5e34,
    image: "iridyum_grandma.webp",
    modifying: {
      building: "Grandma",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Grandma",
      amount: 500,
    },
    tier: "iridyum",
    owned: false,
  },
  {
    name: "Kitchen cabinets",
    description: "Grandmas are twice as efficient.",
    price: 5e38,
    image: "glucosmium_grandma.webp",
    modifying: {
      building: "Grandma",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Grandma",
      amount: 550,
    },
    tier: "glucosmium",
    owned: false,
  },
  {
    name: "Foam-tipped canes",
    description: "Grandmas are twice as efficient.",
    price: 5e42,
    image: "glimmeringue_grandma.webp",
    modifying: {
      building: "Grandma",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Grandma",
      amount: 600,
    },
    tier: "glimmeringue",
    owned: false,
  },
]
