export const IdleverseUpgrades = [
  {
    name: "Manifest destiny",
    description: "Idleverses are twice as efficient.",
    price: 120e21,
    image: "plain_idleverse.webp",
    modifying: {
      building: "Idleverse",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Idleverse",
      amount: 1,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "The multiverse in a nutshell",
    description: "Idleverses are twice as efficient.",
    price: 600e21,
    image: "beryllium_idleverse.webp",
    modifying: {
      building: "Idleverse",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Idleverse",
      amount: 5,
    },
    tier: "beryllium",
    owned: false,
  },
  {
    name: "All-conversion",
    description: "Idleverses are twice as efficient.",
    price: 6e24,
    image: "blueberyllium_idleverse.webp",
    modifying: {
      building: "Idleverse",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Idleverse",
      amount: 25,
    },
    tier: "blueberyllium",
    owned: false,
  },
  {
    name: "Multiverse agents",
    description: "Idleverses are twice as efficient.",
    price: 600e24,
    image: "chalcedhoney_idleverse.webp",
    modifying: {
      building: "Idleverse",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Idleverse",
      amount: 50,
    },
    tier: "chalcedhoney",
    owned: false,
  },
  {
    name: "Escape plan",
    description: "Idleverses are twice as efficient.",
    price: 60e27,
    image: "buttergold_idleverse.webp",
    modifying: {
      building: "Idleverse",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Idleverse",
      amount: 100,
    },
    tier: "buttergold",
    owned: false,
  },
  {
    name: "Game design",
    description: "Idleverses are twice as efficient.",
    price: 6e30,
    image: "sugarmuck_idleverse.webp",
    modifying: {
      building: "Idleverse",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Idleverse",
      amount: 150,
    },
    tier: "sugarmuck",
    owned: false,
  },
  {
    name: "Sandbox universes",
    description: "Idleverses are twice as efficient.",
    price: 6e33,
    image: "jetmint_idleverse.webp",
    modifying: {
      building: "Idleverse",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Idleverse",
      amount: 200,
    },
    tier: "jetmint",
    owned: false,
  },
  {
    name: "Multiverse wars",
    description: "Idleverses are twice as efficient.",
    price: 6e36,
    image: "cherrysilver_idleverse.webp",
    modifying: {
      building: "Idleverse",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Idleverse",
      amount: 250,
    },
    tier: "cherrysilver",
    owned: false,
  },
  {
    name: "Mobile ports",
    description: "Idleverses are twice as efficient.",
    price: 6e39,
    image: "hazelrald_idleverse.webp",
    modifying: {
      building: "Idleverse",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Idleverse",
      amount: 300,
    },
    tier: "hazelrald",
    owned: false,
  },
  {
    name: "Encapsulated realities",
    description: "Idleverses are twice as efficient.",
    price: 6e42,
    image: "mooncandy_idleverse.webp",
    modifying: {
      building: "Idleverse",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Idleverse",
      amount: 350,
    },
    tier: "mooncandy",
    owned: false,
  },
  {
    name: "Extrinsic clicking",
    description: "Idleverses are twice as efficient.",
    price: 60e45,
    image: "astrofudge_idleverse.webp",
    modifying: {
      building: "Idleverse",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Idleverse",
      amount: 400,
    },
    tier: "astrofudge",
    owned: false,
  },
  {
    name: "Universal idling",
    description: "Idleverses are twice as efficient.",
    price: 600e48,
    image: "alabascream_idleverse.webp",
    modifying: {
      building: "Idleverse",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Idleverse",
      amount: 450,
    },
    tier: "alabascream",
    owned: false,
  },
  {
    name: "Break the fifth wall",
    description: "Idleverses are twice as efficient.",
    price: 6e54,
    image: "iridyum_idleverse.webp",
    modifying: {
      building: "Idleverse",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Idleverse",
      amount: 500,
    },
    tier: "iridyum",
    owned: false,
  },
  {
    name: "Opposite universe",
    description: "Idleverses are twice as efficient.",
    price: 60e57,
    image: "glucosmium_idleverse.webp",
    modifying: {
      building: "Idleverse",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Idleverse",
      amount: 550,
    },
    tier: "glucosmium",
    owned: false,
  },
  {
    name: "The other routes to Rome",
    description: "Idleverses are twice as efficient.",
    price: 600e60,
    image: "glimmeringue_idleverse.webp",
    modifying: {
      building: "Idleverse",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Idleverse",
      amount: 600,
    },
    tier: "glimmeringue",
    owned: false,
  },
]