export const JavascriptConsoleUpgrades = [
  {
    name: "The JavaScript console for dummies",
    description: "Javascript consoles are twice as efficient.",
    price: 710e18,
    image: "plain_javascript_console.webp",
    modifying: {
      building: "Javascript Console",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Javascript Console",
      amount: 1,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "64bit arrays",
    description: "Javascript consoles are twice as efficient.",
    price: 3.55e21,
    image: "beryllium_javascript_console.webp",
    modifying: {
      building: "Javascript Console",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Javascript Console",
      amount: 5,
    },
    tier: "beryllium",
    owned: false,
  },
  {
    name: "Stack overflow",
    description: "Javascript consoles are twice as efficient.",
    price: 35.5e21,
    image: "blueberyllium_javascript_console.webp",
    modifying: {
      building: "Javascript Console",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Javascript Console",
      amount: 25,
    },
    tier: "blueberyllium",
    owned: false,
  },
  {
    name: "Enterprise compiler",
    description: "Javascript consoles are twice as efficient.",
    price: 3.55e24,
    image: "chalcedhoney_javascript_console.webp",
    modifying: {
      building: "Javascript Console",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Javascript Console",
      amount: 50,
    },
    tier: "chalcedhoney",
    owned: false,
  },
  {
    name: "Syntactic sugar",
    description: "Javascript consoles are twice as efficient.",
    price: 355e24,
    image: "buttergold_javascript_console.webp",
    modifying: {
      building: "Javascript Console",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Javascript Console",
      amount: 100,
    },
    tier: "buttergold",
    owned: false,
  },
  {
    name: "A nice cup of coffee",
    description: "Javascript consoles are twice as efficient.",
    price: 35.5e27,
    image: "sugarmuck_javascript_console.webp",
    modifying: {
      building: "Javascript Console",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Javascript Console",
      amount: 150,
    },
    tier: "sugarmuck",
    owned: false,
  },
  {
    name: "Just-in-time baking",
    description: "Javascript consoles are twice as efficient.",
    price: 35.5e30,
    image: "jetmint_javascript_console.webp",
    modifying: {
      building: "Javascript Console",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Javascript Console",
      amount: 200,
    },
    tier: "jetmint",
    owned: false,
  },
  {
    name: "cookies++",
    description: "Javascript consoles are twice as efficient.",
    price: 35.5e33,
    image: "cherrysilver_javascript_console.webp",
    modifying: {
      building: "Javascript Console",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Javascript Console",
      amount: 250,
    },
    tier: "cherrysilver",
    owned: false,
  },
  {
    name: "Software updates",
    description: "Javascript consoles are twice as efficient.",
    price: 35.5e36,
    image: "hazelrald_javascript_console.webp",
    modifying: {
      building: "Javascript Console",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Javascript Console",
      amount: 300,
    },
    tier: "hazelrald",
    owned: false,
  },
  {
    name: "Game.Loop",
    description: "Javascript consoles are twice as efficient.",
    price: 35.5e39,
    image: "mooncandy_javascript_console.webp",
    modifying: {
      building: "Javascript Console",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Javascript Console",
      amount: 350,
    },
    tier: "mooncandy",
    owned: false,
  },
  {
    name: "eval()",
    description: "Javascript consoles are twice as efficient.",
    price: 355e42,
    image: "astrofudge_javascript_console.webp",
    modifying: {
      building: "Javascript Console",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Javascript Console",
      amount: 400,
    },
    tier: "astrofudge",
    owned: false,
  },
  {
    name: "Your biggest fans",
    description: "Javascript consoles are twice as efficient.",
    price: 3.55e48,
    image: "alabascream_javascript_console.webp",
    modifying: {
      building: "Javascript Console",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Javascript Console",
      amount: 450,
    },
    tier: "alabascream",
    owned: false,
  },
  {
    name: "Hacker shades",
    description: "Javascript consoles are twice as efficient.",
    price: 35.5e51,
    image: "iridyum_javascript_console.webp",
    modifying: {
      building: "Javascript Console",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Javascript Console",
      amount: 500,
    },
    tier: "iridyum",
    owned: false,
  },
  {
    name: "PHP containment vats",
    description: "Javascript consoles are twice as efficient.",
    price: 355e54,
    image: "glucosmium_javascript_console.webp",
    modifying: {
      building: "Javascript Console",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Javascript Console",
      amount: 550,
    },
    tier: "glucosmium",
    owned: false,
  },
  {
    name: "Simulation failsafes",
    description: "Javascript consoles are twice as efficient.",
    price: 3.55e60,
    image: "glimmeringue_javascript_console.webp",
    modifying: {
      building: "Javascript Console",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Javascript Console",
      amount: 600,
    },
    tier: "glimmeringue",
    owned: false,
  },
]