export const MineUpgrades = [
  {
    name: "Sugar gas",
    description: "Mines are twice as efficient.",
    price: 120e3,
    image: "plain_mine.webp",
    modifying: {
      building: "Mine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Mine",
      amount: 1,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "Megadrill",
    description: "Mines are twice as efficient.",
    price: 600e3,
    image: "beryllium_mine.webp",
    modifying: {
      building: "Mine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Mine",
      amount: 5,
    },
    tier: "beryllium",
    owned: false,
  },
  {
    name: "Ultradrill",
    description: "Mines are twice as efficient.",
    price: 6e6,
    image: "blueberyllium_mine.webp",
    modifying: {
      building: "Mine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Mine",
      amount: 25,
    },
    tier: "blueberyllium",
    owned: false,
  },
  {
    name: "Ultimadrill",
    description: "Mines are twice as efficient.",
    price: 600e6,
    image: "chalcedhoney_mine.webp",
    modifying: {
      building: "Mine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Mine",
      amount: 50,
    },
    tier: "chalcedhoney",
    owned: false,
  },
  {
    name: "H-bomb mining",
    description: "Mines are twice as efficient.",
    price: 60e9,
    image: "buttergold_mine.webp",
    modifying: {
      building: "Mine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Mine",
      amount: 100,
    },
    tier: "buttergold",
    owned: false,
  },
  {
    name: "Coreforge",
    description: "Mines are twice as efficient.",
    price: 6e12,
    image: "sugarmuck_mine.webp",
    modifying: {
      building: "Mine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Mine",
      amount: 150,
    },
    tier: "sugarmuck",
    owned: false,
  },
  {
    name: "Planetsplitters",
    description: "Mines are twice as efficient.",
    price: 6e15,
    image: "jetmint_mine.webp",
    modifying: {
      building: "Mine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Mine",
      amount: 200,
    },
    tier: "jetmint",
    owned: false,
  },
  {
    name: "Canola oil wells",
    description: "Mines are twice as efficient.",
    price: 6e18,
    image: "cherrysilver_mine.webp",
    modifying: {
      building: "Mine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Mine",
      amount: 250,
    },
    tier: "cherrysilver",
    owned: false,
  },
  {
    name: "Mole people",
    description: "Mines are twice as efficient.",
    price: 6e21,
    image: "hazelrald_mine.webp",
    modifying: {
      building: "Mine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Mine",
      amount: 300,
    },
    tier: "hazelrald",
    owned: false,
  },
  {
    name: "Mine canaries",
    description: "Mines are twice as efficient.",
    price: 6e24,
    image: "mooncandy_mine.webp",
    modifying: {
      building: "Mine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Mine",
      amount: 350,
    },
    tier: "mooncandy",
    owned: false,
  },
  {
    name: "Bore again",
    description: "Mines are twice as efficient.",
    price: 60e27,
    image: "astrofudge_mine.webp",
    modifying: {
      building: "Mine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Mine",
      amount: 400,
    },
    tier: "astrofudge",
    owned: false,
  },
  {
    name: "Air mining",
    description: "Mines are twice as efficient.",
    price: 600e30,
    image: "alabascream_mine.webp",
    modifying: {
      building: "Mine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Mine",
      amount: 450,
    },
    tier: "alabascream",
    owned: false,
  },
  {
    name: "Caramel alloys",
    description: "Mines are twice as efficient.",
    price: 6e36,
    image: "iridyum_mine.webp",
    modifying: {
      building: "Mine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Mine",
      amount: 500,
    },
    tier: "iridyum",
    owned: false,
  },
  {
    name: "Delicious mineralogy",
    description: "Mines are twice as efficient.",
    price: 60e39,
    image: "glucosmium_mine.webp",
    modifying: {
      building: "Mine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Mine",
      amount: 550,
    },
    tier: "glucosmium",
    owned: false,
  },
  {
    name: "Mineshaft supports",
    description: "Mines are twice as efficient.",
    price: 600e42,
    image: "glimmeringue_mine.webp",
    modifying: {
      building: "Mine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Mine",
      amount: 600,
    },
    tier: "glimmeringue",
    owned: false,
  },
]