export const PortalUpgrades = [
  {
    name: "Ancient tablet",
    description: "Portals are twice as efficient.",
    price: 10e12,
    image: "plain_portal.webp",
    modifying: {
      building: "Portal",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Portal",
      amount: 1,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "Insane oatling workers",
    description: "Portals are twice as efficient.",
    price: 50e12,
    image: "beryllium_portal.webp",
    modifying: {
      building: "Portal",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Portal",
      amount: 5,
    },
    tier: "beryllium",
    owned: false,
  },
  {
    name: "Soul bond",
    description: "Portals are twice as efficient.",
    price: 500e12,
    image: "blueberyllium_portal.webp",
    modifying: {
      building: "Portal",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Portal",
      amount: 25,
    },
    tier: "blueberyllium",
    owned: false,
  },
  {
    name: "Sanity dance",
    description: "Portals are twice as efficient.",
    price: 50e15,
    image: "chalcedhoney_portal.webp",
    modifying: {
      building: "Portal",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Portal",
      amount: 50,
    },
    tier: "chalcedhoney",
    owned: false,
  },
  {
    name: "Brane transplant",
    description: "Portals are twice as efficient.",
    price: 5e18,
    image: "buttergold_portal.webp",
    modifying: {
      building: "Portal",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Portal",
      amount: 100,
    },
    tier: "buttergold",
    owned: false,
  },
  {
    name: "Deity-sized portals",
    description: "Portals are twice as efficient.",
    price: 500e18,
    image: "sugarmuck_portal.webp",
    modifying: {
      building: "Portal",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Portal",
      amount: 150,
    },
    tier: "sugarmuck",
    owned: false,
  },
  {
    name: "End of times back-up plan",
    description: "Portals are twice as efficient.",
    price: 500e21,
    image: "jetmint_portal.webp",
    modifying: {
      building: "Portal",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Portal",
      amount: 200,
    },
    tier: "jetmint",
    owned: false,
  },
  {
    name: "Maddening chants",
    description: "Portals are twice as efficient.",
    price: 500e24,
    image: "cherrysilver_portal.webp",
    modifying: {
      building: "Portal",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Portal",
      amount: 250,
    },
    tier: "cherrysilver",
    owned: false,
  },
  {
    name: "The real world",
    description: "Portals are twice as efficient.",
    price: 500e27,
    image: "hazelrald_portal.webp",
    modifying: {
      building: "Portal",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Portal",
      amount: 300,
    },
    tier: "hazelrald",
    owned: false,
  },
  {
    name: "Dimensional garbage gulper",
    description: "Portals are twice as efficient.",
    price: 500e30,
    image: "mooncandy_portal.webp",
    modifying: {
      building: "Portal",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Portal",
      amount: 350,
    },
    tier: "mooncandy",
    owned: false,
  },
  {
    name: "Embedded microportals",
    description: "Portals are twice as efficient.",
    price: 5e36,
    image: "astrofudge_portal.webp",
    modifying: {
      building: "Portal",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Portal",
      amount: 400,
    },
    tier: "astrofudge",
    owned: false,
  },
  {
    name: "His advent",
    description: "Portals are twice as efficient.",
    price: 50e39,
    image: "alabascream_portal.webp",
    modifying: {
      building: "Portal",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Portal",
      amount: 450,
    },
    tier: "alabascream",
    owned: false,
  },
  {
    name: "Domestic rifts",
    description: "Portals are twice as efficient.",
    price: 500e42,
    image: "iridyum_portal.webp",
    modifying: {
      building: "Portal",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Portal",
      amount: 500,
    },
    tier: "iridyum",
    owned: false,
  },
  {
    name: "Portal guns",
    description: "Portals are twice as efficient.",
    price: 5e48,
    image: "glucosmium_portal.webp",
    modifying: {
      building: "Portal",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Portal",
      amount: 550,
    },
    tier: "glucosmium",
    owned: false,
  },
  {
    name: "A way home",
    description: "Portals are twice as efficient.",
    price: 50e51,
    image: "glimmeringue_portal.webp",
    modifying: {
      building: "Portal",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Portal",
      amount: 600,
    },
    tier: "glimmeringue",
    owned: false,
  },
]