export const PrismUpgrades = [
  {
    name: "Gem polish",
    description: "Prisms are twice as efficient.",
    price: 21e15,
    image: "prism/plain_prism.webp",
    modifying: {
      building: "Prism",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Prism",
      amount: 1,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "9th color",
    description: "Prisms are twice as efficient.",
    price: 105e15,
    image: "prism/beryllium_prism.webp",
    modifying: {
      building: "Prism",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Prism",
      amount: 5,
    },
    tier: "beryllium",
    owned: false,
  },
  {
    name: "Chocolate light",
    description: "Prisms are twice as efficient.",
    price: 1.05e18,
    image: "prism/blueberyllium_prism.webp",
    modifying: {
      building: "Prism",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Prism",
      amount: 25,
    },
    tier: "blueberyllium",
    owned: false,
  },
  {
    name: "Grainbow",
    description: "Prisms are twice as efficient.",
    price: 105e18,
    image: "prism/chalcedhoney_prism.webp",
    modifying: {
      building: "Prism",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Prism",
      amount: 50,
    },
    tier: "chalcedhoney",
    owned: false,
  },
  {
    name: "Pure cosmic light",
    description: "Prisms are twice as efficient.",
    price: 10.5e21,
    image: "prism/buttergold_prism.webp",
    modifying: {
      building: "Prism",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Prism",
      amount: 100,
    },
    tier: "buttergold",
    owned: false,
  },
  {
    name: "Glow-in-the-dark",
    description: "Prisms are twice as efficient.",
    price: 1.05e24,
    image: "prism/sugarmuck_prism.webp",
    modifying: {
      building: "Prism",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Prism",
      amount: 150,
    },
    tier: "sugarmuck",
    owned: false,
  },
  {
    name: "Lux sanctorum",
    description: "Prisms are twice as efficient.",
    price: 1.05e27,
    image: "prism/jetmint_prism.webp",
    modifying: {
      building: "Prism",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Prism",
      amount: 200,
    },
    tier: "jetmint",
    owned: false,
  },
  {
    name: "Reverse shadows",
    description: "Prisms are twice as efficient.",
    price: 1.05e30,
    image: "prism/cherrysilver_prism.webp",
    modifying: {
      building: "Prism",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Prism",
      amount: 250,
    },
    tier: "cherrysilver",
    owned: false,
  },
  {
    name: "Crystal mirrors",
    description: "Prisms are twice as efficient.",
    price: 1.05e33,
    image: "prism/hazelrald_prism.webp",
    modifying: {
      building: "Prism",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Prism",
      amount: 300,
    },
    tier: "hazelrald",
    owned: false,
  },
  {
    name: "Reverse theory of light",
    description: "Prisms are twice as efficient.",
    price: 1.05e36,
    image: "prism/mooncandy_prism.webp",
    modifying: {
      building: "Prism",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Prism",
      amount: 350,
    },
    tier: "mooncandy",
    owned: false,
  },
  {
    name: "Light capture measures",
    description: "Prisms are twice as efficient.",
    price: 10.5e39,
    image: "prism/astrofudge_prism.webp",
    modifying: {
      building: "Prism",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Prism",
      amount: 400,
    },
    tier: "astrofudge",
    owned: false,
  },
  {
    name: "Light speed limit",
    description: "Prisms are twice as efficient.",
    price: 105e42,
    image: "prism/alabascream_prism.webp",
    modifying: {
      building: "Prism",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Prism",
      amount: 450,
    },
    tier: "alabascream",
    owned: false,
  },
  {
    name: "Occam's laser",
    description: "Prisms are twice as efficient.",
    price: 1.05e48,
    image: "prism/iridyum_prism.webp",
    modifying: {
      building: "Prism",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Prism",
      amount: 500,
    },
    tier: "iridyum",
    owned: false,
  },
  {
    name: "Hyperblack paint",
    description: "Prisms are twice as efficient.",
    price: 10.5e51,
    image: "prism/glucosmium_prism.webp",
    modifying: {
      building: "Prism",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Prism",
      amount: 550,
    },
    tier: "glucosmium",
    owned: false,
  },
  {
    name: "Lab goggles but like cool shades",
    description: "Prisms are twice as efficient.",
    price: 105e54,
    image: "prism/glimmeringue_prism.webp",
    modifying: {
      building: "Prism",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Prism",
      amount: 600,
    },
    tier: "glimmeringue",
    owned: false,
  },
]