export const TempleUpgrades = [
  {
    name: "Golden idols",
    description: "Temples are twice as efficient.",
    price: 200e6,
    image: "temple/plain_temple.webp",
    modifying: {
      building: "Temple",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Temple",
      amount: 1,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "Sacrifices",
    description: "Temples are twice as efficient.",
    price: 1e9,
    image: "beryllium_.webp",
    modifying: {
      building: "Temple",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Temple",
      amount: 5,
    },
    tier: "beryllium",
    owned: false,
  },
  {
    name: "Delicious blessing",
    description: "Temples are twice as efficient.",
    price: 10e9,
    image: "blueberyllium_.webp",
    modifying: {
      building: "Temple",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Temple",
      amount: 25,
    },
    tier: "blueberyllium",
    owned: false,
  },
  {
    name: "Sun festival",
    description: "Temples are twice as efficient.",
    price: 1e12,
    image: "chalcedhoney_.webp",
    modifying: {
      building: "Temple",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Temple",
      amount: 50,
    },
    tier: "chalcedhoney",
    owned: false,
  },
  {
    name: "Enlarged pantheon",
    description: "Temples are twice as efficient.",
    price: 100e12,
    image: "buttergold_.webp",
    modifying: {
      building: "Temple",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Temple",
      amount: 100,
    },
    tier: "buttergold",
    owned: false,
  },
  {
    name: "Great Baker in the sky",
    description: "Temples are twice as efficient.",
    price: 10e15,
    image: "sugarmuck_.webp",
    modifying: {
      building: "Temple",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Temple",
      amount: 150,
    },
    tier: "sugarmuck",
    owned: false,
  },
  {
    name: "Creation myth",
    description: "Temples are twice as efficient.",
    price: 10e18,
    image: "jetmint_.webp",
    modifying: {
      building: "Temple",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Temple",
      amount: 200,
    },
    tier: "jetmint",
    owned: false,
  },
  {
    name: "Theocracy",
    description: "Temples are twice as efficient.",
    price: 10e21,
    image: "cherrysilver_.webp",
    modifying: {
      building: "Temple",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Temple",
      amount: 250,
    },
    tier: "cherrysilver",
    owned: false,
  },
  {
    name: "Sick rap prayers",
    description: "Temples are twice as efficient.",
    price: 10e24,
    image: "hazelrald_.webp",
    modifying: {
      building: "Temple",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Temple",
      amount: 300,
    },
    tier: "hazelrald",
    owned: false,
  },
  {
    name: "Psalm-reading",
    description: "Temples are twice as efficient.",
    price: 10e27,
    image: "mooncandy_.webp",
    modifying: {
      building: "Temple",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Temple",
      amount: 350,
    },
    tier: "mooncandy",
    owned: false,
  },
  {
    name: "War of the gods",
    description: "Temples are twice as efficient.",
    price: 100e30,
    image: "astrofudge_.webp",
    modifying: {
      building: "Temple",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Temple",
      amount: 400,
    },
    tier: "astrofudge",
    owned: false,
  },
  {
    name: "A novel idea",
    description: "Temples are twice as efficient.",
    price: 1e36,
    image: "alabascream_.webp",
    modifying: {
      building: "Temple",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Temple",
      amount: 450,
    },
    tier: "alabascream",
    owned: false,
  },
  {
    name: "Apparitions",
    description: "Temples are twice as efficient.",
    price: 10e39,
    image: "iridyum_.webp",
    modifying: {
      building: "Temple",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Temple",
      amount: 500,
    },
    tier: "iridyum",
    owned: false,
  },
  {
    name: "Negatheism",
    description: "Temples are twice as efficient.",
    price: 100e42,
    image: "glucosmium_.webp",
    modifying: {
      building: "Temple",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Temple",
      amount: 550,
    },
    tier: "glucosmium",
    owned: false,
  },
  {
    name: "Temple traps",
    description: "Temples are twice as efficient.",
    price: 1e48,
    image: "glimmeringue_.webp",
    modifying: {
      building: "Temple",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Temple",
      amount: 600,
    },
    tier: "glimmeringue",
    owned: false,
  },
]