export const TimeMachineUpgrades = [
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "plain_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 1,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "beryllium_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 5,
    },
    tier: "beryllium",
    owned: false,
  },
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "blueberyllium_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 25,
    },
    tier: "blueberyllium",
    owned: false,
  },
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "chalcedhoney_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 50,
    },
    tier: "chalcedhoney",
    owned: false,
  },
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "buttergold_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 100,
    },
    tier: "buttergold",
    owned: false,
  },
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "sugarmuck_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 150,
    },
    tier: "sugarmuck",
    owned: false,
  },
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "jetmint_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 200,
    },
    tier: "jetmint",
    owned: false,
  },
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "cherrysilver_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 250,
    },
    tier: "cherrysilver",
    owned: false,
  },
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "hazelrald_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 300,
    },
    tier: "hazelrald",
    owned: false,
  },
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "mooncandy_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 350,
    },
    tier: "mooncandy",
    owned: false,
  },
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "astrofudge_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 400,
    },
    tier: "astrofudge",
    owned: false,
  },
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "alabascream_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 450,
    },
    tier: "alabascream",
    owned: false,
  },
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "iridyum_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 500,
    },
    tier: "iridyum",
    owned: false,
  },
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "glucosmium_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 550,
    },
    tier: "glucosmium",
    owned: false,
  },
  {
    name: "",
    description: "are twice as efficient.",
    price: 0,
    image: "glimmeringue_.webp",
    modifying: {
      building: "",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "",
      amount: 600,
    },
    tier: "glimmeringue",
    owned: false,
  },
]