export const TimeMachineUpgrades = [
  {
    name: "Flux capacitors",
    description: "Time machines are twice as efficient.",
    price: 140e12,
    image: "plain_time_machine.webp",
    modifying: {
      building: "Time Machine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Time Machine",
      amount: 1,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "Time paradox resolverFlux capacitors",
    description: "Time machines are twice as efficient.",
    price: 700e12,
    image: "beryllium_time_machine.webp",
    modifying: {
      building: "Time Machine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Time Machine",
      amount: 5,
    },
    tier: "beryllium",
    owned: false,
  },
  {
    name: "Quantum cocundrum",
    description: "Time machines are twice as efficient.",
    price: 7e15,
    image: "blueberyllium_time_machine.webp",
    modifying: {
      building: "Time Machine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Time Machine",
      amount: 25,
    },
    tier: "blueberyllium",
    owned: false,
  },
  {
    name: "Casuality enforcer",
    description: "Time machines are twice as efficient.",
    price: 700e15,
    image: "chalcedhoney_time_machine.webp",
    modifying: {
      building: "Time Machine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Time Machine",
      amount: 50,
    },
    tier: "chalcedhoney",
    owned: false,
  },
  {
    name: "Yestermorrow comparators",
    description: "Time machines are twice as efficient.",
    price: 70e18,
    image: "buttergold_time_machine.webp",
    modifying: {
      building: "Time Machine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Time Machine",
      amount: 100,
    },
    tier: "buttergold",
    owned: false,
  },
  {
    name: "Far future enactment",
    description: "Time machines are twice as efficient.",
    price: 7e21,
    image: "sugarmuck_time_machine.webp",
    modifying: {
      building: "Time Machine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Time Machine",
      amount: 150,
    },
    tier: "sugarmuck",
    owned: false,
  },
  {
    name: "Great loop hypothesis",
    description: "Time machines are twice as efficient.",
    price: 7e24,
    image: "jetmint_time_machine.webp",
    modifying: {
      building: "Time Machine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Time Machine",
      amount: 200,
    },
    tier: "jetmint",
    owned: false,
  },
  {
    name: "Cookietopian moments of maybe",
    description: "Time machines are twice as efficient.",
    price: 7e27,
    image: "cherrysilver_time_machine.webp",
    modifying: {
      building: "Time Machine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Time Machine",
      amount: 250,
    },
    tier: "cherrysilver",
    owned: false,
  },
  {
    name: "Second seconds",
    description: "Time machines are twice as efficient.",
    price: 7e30,
    image: "hazelrald_time_machine.webp",
    modifying: {
      building: "Time Machine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Time Machine",
      amount: 300,
    },
    tier: "hazelrald",
    owned: false,
  },
  {
    name: "Additional clock hands",
    description: "Time machines are twice as efficient.",
    price: 7e33,
    image: "mooncandy_time_machine.webp",
    modifying: {
      building: "Time Machine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Time Machine",
      amount: 350,
    },
    tier: "mooncandy",
    owned: false,
  },
  {
    name: "Nostalgia",
    description: "Time machines are twice as efficient.",
    price: 70e36,
    image: "astrofudge_time_machine.webp",
    modifying: {
      building: "Time Machine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Time Machine",
      amount: 400,
    },
    tier: "astrofudge",
    owned: false,
  },
  {
    name: "Split seconds",
    description: "Time machines are twice as efficient.",
    price: 700e39,
    image: "alabascream_time_machine.webp",
    modifying: {
      building: "Time Machine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Time Machine",
      amount: 450,
    },
    tier: "alabascream",
    owned: false,
  },
  {
    name: "Patience abolished",
    description: "Time machines are twice as efficient.",
    price: 7e45,
    image: "iridyum_time_machine.webp",
    modifying: {
      building: "Time Machine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Time Machine",
      amount: 500,
    },
    tier: "iridyum",
    owned: false,
  },
  {
    name: "Timeproof upholstery",
    description: "Time machines are twice as efficient.",
    price: 70e48,
    image: "glucosmium_time_machine.webp",
    modifying: {
      building: "Time Machine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Time Machine",
      amount: 550,
    },
    tier: "glucosmium",
    owned: false,
  },
  {
    name: "Rectifying a mistake",
    description: "Time machines are twice as efficient.",
    price: 700e51,
    image: "glimmeringue_time_machine.webp",
    modifying: {
      building: "Time Machine",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Time Machine",
      amount: 600,
    },
    tier: "glimmeringue",
    owned: false,
  },
]