export const WizardTowerUpgrades = [
  {
    name: "Pointier hats",
    description: "Wizard towers are twice as efficient.",
    price: 3.3e9,
    image: "wizard_tower/plain_wizard_tower.webp",
    modifying: {
      building: "Wizard Tower",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Wizard Tower",
      amount: 1,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "Beardlier beards",
    description: "Wizard towers are twice as efficient.",
    price: 16.5e9,
    image: "beryllium_.webp",
    modifying: {
      building: "Wizard Tower",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Wizard Tower",
      amount: 5,
    },
    tier: "beryllium",
    owned: false,
  },
  {
    name: "Ancient grimoires",
    description: "Wizard towers are twice as efficient.",
    price: 165e9,
    image: "blueberyllium_.webp",
    modifying: {
      building: "Wizard Tower",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Wizard Tower",
      amount: 25,
    },
    tier: "blueberyllium",
    owned: false,
  },
  {
    name: "Kitchen curses",
    description: "Wizard towers are twice as efficient.",
    price: 16.5e12,
    image: "chalcedhoney_.webp",
    modifying: {
      building: "Wizard Tower",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Wizard Tower",
      amount: 50,
    },
    tier: "chalcedhoney",
    owned: false,
  },
  {
    name: "School of discovery",
    description: "Wizard towers are twice as efficient.",
    price: 1.65e15,
    image: "buttergold_.webp",
    modifying: {
      building: "Wizard Tower",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Wizard Tower",
      amount: 100,
    },
    tier: "buttergold",
    owned: false,
  },
  {
    name: "Dark formulas",
    description: "Wizard towers are twice as efficient.",
    price: 165e15,
    image: "sugarmuck_.webp",
    modifying: {
      building: "Wizard Tower",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Wizard Tower",
      amount: 150,
    },
    tier: "sugarmuck",
    owned: false,
  },
  {
    name: "Cookiemancy",
    description: "Wizard towers are twice as efficient.",
    price: 165e18,
    image: "jetmint_.webp",
    modifying: {
      building: "Wizard Tower",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Wizard Tower",
      amount: 200,
    },
    tier: "jetmint",
    owned: false,
  },
  {
    name: "Rabbit trick",
    description: "Wizard towers are twice as efficient.",
    price: 165e21,
    image: "cherrysilver_.webp",
    modifying: {
      building: "Wizard Tower",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Wizard Tower",
      amount: 250,
    },
    tier: "cherrysilver",
    owned: false,
  },
  {
    name: "Deluxe tailored wands",
    description: "Wizard towers are twice as efficient.",
    price: 165e24,
    image: "hazelrald_.webp",
    modifying: {
      building: "Wizard Tower",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Wizard Tower",
      amount: 300,
    },
    tier: "hazelrald",
    owned: false,
  },
  {
    name: "Immobile spellcasting",
    description: "Wizard towers are twice as efficient.",
    price: 165e27,
    image: "mooncandy_.webp",
    modifying: {
      building: "Wizard Tower",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Wizard Tower",
      amount: 350,
    },
    tier: "mooncandy",
    owned: false,
  },
  {
    name: "Electricity",
    description: "Wizard towers are twice as efficient.",
    price: 1.65e33,
    image: "astrofudge_.webp",
    modifying: {
      building: "Wizard Tower",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Wizard Tower",
      amount: 400,
    },
    tier: "astrofudge",
    owned: false,
  },
  {
    name: "Spelling bees",
    description: "Wizard towers are twice as efficient.",
    price: 16.5e36,
    image: "alabascream_.webp",
    modifying: {
      building: "Wizard Tower",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Wizard Tower",
      amount: 450,
    },
    tier: "alabascream",
    owned: false,
  },
  {
    name: "Wizard basements",
    description: "Wizard towers are twice as efficient.",
    price: 165e39,
    image: "iridyum_.webp",
    modifying: {
      building: "Wizard Tower",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Wizard Tower",
      amount: 500,
    },
    tier: "iridyum",
    owned: false,
  },
  {
    name: "Magical realism",
    description: "Wizard towers are twice as efficient.",
    price: 1.65e45,
    image: "glucosmium_.webp",
    modifying: {
      building: "Wizard Tower",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Wizard Tower",
      amount: 550,
    },
    tier: "glucosmium",
    owned: false,
  },
  {
    name: "Polymorphism",
    description: "Wizard towers are twice as efficient.",
    price: 16.5e48,
    image: "glimmeringue_.webp",
    modifying: {
      building: "Wizard Tower",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "Wizard Tower",
      amount: 600,
    },
    tier: "glimmeringue",
    owned: false,
  },
]