export const YouUpgrades = [
  {
    name: "Cloning vats",
    description: "You are twice as efficient.",
    price: 5.4e27,
    image: "you/plain_you.webp",
    modifying: {
      building: "You",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "You",
      amount: 1,
    },
    tier: "plain",
    owned: false,
  },
  {
    name: "Energized nutrients",
    description: "You are twice as efficient.",
    price: 27e27,
    image: "you/beryllium_you.webp",
    modifying: {
      building: "You",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "You",
      amount: 5,
    },
    tier: "beryllium",
    owned: false,
  },
  {
    name: "Stunt doubles",
    description: "You are twice as efficient.",
    price: 270e27,
    image: "you/blueberyllium_you.webp",
    modifying: {
      building: "You",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "You",
      amount: 25,
    },
    tier: "blueberyllium",
    owned: false,
  },
  {
    name: "Clone recycling plant",
    description: "You are twice as efficient.",
    price: 27e30,
    image: "you/chalcedhoney_you.webp",
    modifying: {
      building: "You",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "You",
      amount: 50,
    },
    tier: "chalcedhoney",
    owned: false,
  },
  {
    name: "Free-range clones",
    description: "You are twice as efficient.",
    price: 2.7e33,
    image: "you/buttergold_you.webp",
    modifying: {
      building: "You",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "You",
      amount: 100,
    },
    tier: "buttergold",
    owned: false,
  },
  {
    name: "Genetic tailoring",
    description: "You are twice as efficient.",
    price: 270e33,
    image: "you/sugarmuck_you.webp",
    modifying: {
      building: "You",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "You",
      amount: 150,
    },
    tier: "sugarmuck",
    owned: false,
  },
  {
    name: "Power in diversity",
    description: "You are twice as efficient.",
    price: 270e36,
    image: "you/jetmint_you.webp",
    modifying: {
      building: "You",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "You",
      amount: 200,
    },
    tier: "jetmint",
    owned: false,
  },
  {
    name: "Self-betterment",
    description: "You are twice as efficient.",
    price: 270e39,
    image: "you/cherrysilver_you.webp",
    modifying: {
      building: "You",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "You",
      amount: 250,
    },
    tier: "cherrysilver",
    owned: false,
  },
  {
    name: "Source control",
    description: "You are twice as efficient.",
    price: 270e42,
    image: "you/hazelrald_you.webp",
    modifying: {
      building: "You",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "You",
      amount: 300,
    },
    tier: "hazelrald",
    owned: false,
  },
  {
    name: "United workforce",
    description: "You are twice as efficient.",
    price: 270e45,
    image: "you/mooncandy_you.webp",
    modifying: {
      building: "You",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "You",
      amount: 350,
    },
    tier: "mooncandy",
    owned: false,
  },
  {
    name: "Safety patrols",
    description: "You are twice as efficient.",
    price: 2.7e51,
    image: "you/astrofudge_you.webp",
    modifying: {
      building: "You",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "You",
      amount: 400,
    },
    tier: "astrofudge",
    owned: false,
  },
  {
    name: "Clone rights",
    description: "You are twice as efficient.",
    price: 27e54,
    image: "you/alabascream_you.webp",
    modifying: {
      building: "You",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "You",
      amount: 450,
    },
    tier: "alabascream",
    owned: false,
  },
  {
    name: "One big family",
    description: "You are twice as efficient.",
    price: 270e57,
    image: "you/iridyum_you.webp",
    modifying: {
      building: "You",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "You",
      amount: 500,
    },
    tier: "iridyum",
    owned: false,
  },
  {
    name: "Fine-tuned body plans",
    description: "You are twice as efficient.",
    price: 2.7e63,
    image: "you/glucosmium_you.webp",
    modifying: {
      building: "You",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "You",
      amount: 550,
    },
    tier: "glucosmium",
    owned: false,
  },
  {
    name: "Reading your clones bedtime stories",
    description: "You are twice as efficient.",
    price: 27e66,
    image: "you/glimmeringue_you.webp",
    modifying: {
      building: "You",
    },
    modifyingValue: 2.0,
    unlockCondition: {
      building: "You",
      amount: 600,
    },
    tier: "glimmeringue",
    owned: false,
  },
]